language: generic
sudo: required
services:
  - docker

# build a dev image to have the Recat src code to runs tests
# prod image doesn't have code to run tests against
# before_install:
#   - docker build -t siyanththan/react-test -f ./client/Dockerfile.dev ./client

# run tests
# script:
#   - docker run -e CI=true siyanththan/react-test npm test

# build prod versions of images of each project using the Dockerfile
after_success:
  - docker build -t siyanththan/multi-container-client ./client
  - docker build -t siyanththan/multi-container-nginx ./nginx
  - docker build -t siyanththan/multi-container-server ./server 
  - docker build -t siyanththan/multi-container-worker ./worker

# login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push the built prod images to docker hub
  - docker push siyanththan/multi-container-client
  - docker push siyanththan/multi-container-nginx
  - docker push siyanththan/multi-container-server 
  - docker push siyanththan/multi-container-worker